# Generated by Django 5.2.1 on 2025-06-04 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_project_delete_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('invoiceNumber', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('customerName', models.CharField(max_length=100)),
                ('billingAddress', models.CharField(max_length=100)),
                ('shippingAddress', models.CharField(max_length=100)),
                ('GSTIN', models.CharField(max_length=100)),
                ('totalAmount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.invoiceheader')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceSundry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billSundryName', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('invoiceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sundries', to='api.invoiceheader')),
            ],
        ),
    ]
