# Generated by Django 5.2.1 on 2025-06-04 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_invoiceheader_invoiceitem_invoicesundry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceheader',
            name='totalAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoicesundry',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
