# Generated by Django 5.2.1 on 2025-06-04 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_tasks_remove_invoicesundry_invoiceid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tasks',
            name='due_date',
            field=models.DateField(default=datetime.date(2025, 6, 4)),
        ),
        migrations.AddField(
            model_name='tasks',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='High', max_length=100),
        ),
    ]
