# Generated by Django 5.2.1 on 2025-06-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_tasks_description_tasks_due_date_tasks_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('Rent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Bedroom', models.IntegerField(max_length=20)),
                ('Posted', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Tasks',
        ),
    ]
