# Generated by Django 5.2.1 on 2025-06-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_apartments_delete_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartments',
            name='city',
            field=models.CharField(default='Hyderabad'),
            preserve_default=False,
        ),
    ]
