# Generated by Django 5.2.1 on 2025-06-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_apartments_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartments',
            name='city',
            field=models.CharField(max_length=100),
        ),
    ]
